# For a guide on now to set environment variables see
# https://docs.netlify.com/configure-builds/environment-variables/

[build.environment]
  # use the latest stable node version
  NODE_VERSION = "16"
